<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25522" started-at="2014-10-07T14:42:40Z" finished-at="2014-10-07T14:43:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25522" started-at="2014-10-07T14:42:40Z" finished-at="2014-10-07T14:43:06Z">
      <class name="Test.letterFromUser1GoToSpamFolder">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Test.letterFromUser1GoToSpamFolder@4d9f6ce5]" name="beforeTest" is-config="true" duration-ms="25499" started-at="2014-10-07T17:42:40Z" finished-at="2014-10-07T17:43:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="FirstUserSendMessageToSecondUser(Object.Email, Object.Users, Object.Email, utils.Utils, Object.Email)[pri:0, instance:Test.letterFromUser1GoToSpamFolder@4d9f6ce5]" name="FirstUserSendMessageToSecondUser" duration-ms="0" started-at="2014-10-07T17:43:06Z" finished-at="2014-10-07T17:43:06Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method FirstUserSendMessageToSecondUser requires 5 parameters but 0 were supplied in the @Test annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method FirstUserSendMessageToSecondUser requires 5 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:198)
	at org.testng.internal.Parameters.createParameters(Parameters.java:134)
	at org.testng.internal.Parameters.createParameters(Parameters.java:373)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:450)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FirstUserSendMessageToSecondUser -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Test.letterFromUser1GoToSpamFolder@4d9f6ce5]" name="afterTest" is-config="true" duration-ms="0" started-at="2014-10-07T17:43:06Z" finished-at="2014-10-07T17:43:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Test.letterFromUser1GoToSpamFolder -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
